# fly.toml app configuration file generated for open-webui-pg on 2024-05-05T22:14:11+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'open-webui-pg'
primary_region = 'ord'

[build]
  image = "ghcr.io/open-webui/open-webui:main"

[env]
  DEFAULT_MODEL = 'llama3.1:8b'
  OLLAMA_BASE_URL = 'http://ollama-pg.internal:11434'
  ENABLE_SIGNUP = 'false'

[[mounts]]
  source = 'data'
  destination = './data'
  initial_size = '10gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
