# fly.toml app configuration file generated for librechat-pg on 2024-05-06T12:48:14+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'librechat-pg'
primary_region = 'otp'

[build]

[env]
  ALLOW_REGISTRATION = 'false'
  HOST = '0.0.0.0'
  MONGO_URI = 'mongodb://librechat-pg-mongod.internal:27017/LibreChat'

[[mounts]]
  source = 'librechat_data'
  destination = '/app/api/logs'
  processes = ['app']

[http_service]
  internal_port = 3080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
