app = "linkding"
primary_region = "fra"

[build]
  image = "sissbruecker/linkding:latest"

[http_service]
  internal_port = 9090
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "linkding_data"
  destination = "/etc/linkding/data"
  processes = ["app"]