app = "searxng"
primary_region = "fra"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "searxng_data"
  destination = "/etc/searxng"
  processes = ["app"]

[env]
  PORT = "8080"
  INSTANCE_NAME = "SearXNG"
  SEARXNG_BASE_URL = "https://searxng-pg.fly.dev/"
  SEARXNG_REDIS_URL = "redis://searxng-pg-redis.internal:6379/0"
