app = "md-to-pdf"
primary_region = "fra"

[build]
  image = "spawnia/md-to-pdf"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ROCKET_LIMITS = "{form=\"1MiB\"}"