# fly.toml app configuration file generated for ollama-pg on 2024-05-07T14:23:02+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ollama-pg'
primary_region = 'ord'

[build]
  image = 'ollama/ollama'

[[mounts]]
  source = 'ollama'
  destination = '/root/.ollama'
  initial_size = '30gb'

[http_service]
  internal_port = 11434
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-8x'
  memory = '16gb'
  gpu_kind = 'l40s'
