name: Deploy

on:
  workflow_dispatch:
    inputs:
      apps:
        description: 'Apps to deploy (comma-separated, or "all")'
        required: true
        default: 'all'
      environment:
        description: 'Environment suffix (leave empty to use ENVIRONMENT secret)'
        required: false
        default: ''
      region:
        description: 'Deployment region'  
        required: false
        default: 'fra'

jobs:
  discover:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.apps.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - id: apps
        run: echo "matrix=$(make matrix apps='${{ inputs.apps }}')" >> $GITHUB_OUTPUT

  deploy:
    name: deploy (worker ${{ matrix.worker }})
    needs: discover
    if: needs.discover.outputs.matrix != '[]'
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        worker: [1, 2, 3, 4]
      fail-fast: false
    env:
      WORKER_COUNT: 4
    steps:
      - uses: actions/checkout@v4
      - name: Install Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "/home/runner/.fly/bin" >> $GITHUB_PATH
      - name: Deploy apps
        run: .github/scripts/deploy-worker.sh ${{ matrix.worker }} ${{ env.WORKER_COUNT }} '${{ inputs.apps }}' '${{ inputs.environment }}' '${{ inputs.region }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          ENVIRONMENT_SECRET: ${{ secrets.ENVIRONMENT }}