name: Deploy Librechat
on:
  push:
    branches:
      - main
    paths:
      - 'librechat/**'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          cd librechat
          flyctl deploy --remote-only
          FLY_APP=librechat-pg-mongod flyctl -c fly.mongod.toml deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}