name: Deploy SearXNG
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'searxng/**'
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: |
          cd searxng
          flyctl deploy --remote-only
          FLY_APP=searxng-pg-redis flyctl -c fly.redis.toml deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}